mythtv:
  image: willat8/mythtv:20210601
  restart: always
  volumes_from:
    - mariadb
    - shepherd
  volumes:
    - "mythtvconfig:/etc/mythtv"
    - "mythtvhome:/root/.mythtv"
    - "/mnt/mythtvdisk:/mnt/storage"
  net: host
  labels:
    io.rancher.os.after: mariadb,shepherd

mariadb:
  image: mariadb:10.3
  restart: always
  volumes:
    - "mariadbsock:/var/run/mysqld"
    - "mythconverg:/var/lib/mysql"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: mythconverg
    MYSQL_USER: mythtv
    MYSQL_PASSWORD: mythtv

shepherd:
  image: willat8/shepherd:20210601
  restart: always
  volumes:
    - "shepherd_output:/shepherd_output"

