zfs-healthcheck:
  image: zfs-tools
  restart: always
  privileged: yes
  pid: host
  net: host
  ipc: host
  volumes:
    - /mnt:/mnt:shared
    - /media:/media:shared
    - /dev:/host/dev
    - /run:/run
  entrypoint: ["python", "-c"]
  command: ["import subprocess, BaseHTTPServer; BaseHTTPServer.HTTPServer(('', 80), type('handler', (BaseHTTPServer.BaseHTTPRequestHandler, object), {'do_GET': lambda s: (s.send_response(200), s.send_header('Content-Type', 'text/plain'), s.end_headers(), s.wfile.write(subprocess.check_output(['zpool', 'status', '-x'])))})).serve_forever()"]
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: mythtv

mythtv:
  image: willat8/mythtv:20210601
  restart: always
  volumes_from:
    - mariadb
    - shepherd
  volumes:
    - "mythtvconfig:/etc/mythtv"
    - "mythtvhome:/root/.mythtv"
    - "/mnt/mythtvzpool:/mnt/storage"
  net: host
  labels:
    io.rancher.os.after: mariadb,shepherd

mariadb:
  image: mariadb:10.3
  restart: always
  volumes:
    - "mariadbsock:/var/run/mysqld"
    - "mythconverg:/var/lib/mysql"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: mythconverg
    MYSQL_USER: mythtv
    MYSQL_PASSWORD: mythtv

shepherd:
  image: willat8/shepherd:20210601
  restart: always
  volumes:
    - "shepherd_output:/shepherd_output"

