apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /media/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rancher

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mythtv-pv
spec:
  capacity:
    storage: 1820Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /media/mythtv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rancher

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: local-storage
  volumeName: mariadb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mythtv-configmap
data:
  config.xml: |
    <Configuration>
      <Database>
        <PingHost>1</PingHost>
        <Host>mariadb</Host>
        <UserName>root</UserName>
        <Password>root</Password>
        <DatabaseName>mythconverg</DatabaseName>
        <Port>3306</Port>
      </Database>
      <WakeOnLAN>
        <Enabled>0</Enabled>
        <SQLReconnectWaitTime>0</SQLReconnectWaitTime>
        <SQLConnectRetry>5</SQLConnectRetry>
        <Command>echo 'WOLsqlServerCommand not set'</Command>
      </WakeOnLAN>
    </Configuration>

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mythtv
spec:
  serviceName: "mythbackend"
  replicas: 1
  selector:
    matchLabels:
      app: mythbackend
  template:
    metadata:
      labels:
        app: mythbackend
    spec:
      containers:
      - name: mythbackend
        image: willat8/mythtv:20210829
        volumeMounts:
        - name: mythtv-data
          mountPath: "/mnt/storage/mythtv"
        - name: mythtv-config
          mountPath: "/root/.mythtv"
        - name: shepherd-data
          mountPath: "/shepherd_output"
      volumes:
      - name: mythtv-config
        configMap:
          name: mythtv-configmap
          items:
          - key: "config.xml"
            path: "config.xml"
      - name: shepherd-data
        persistentVolumeClaim:
          claimName: shepherd-pv-claim
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
  volumeClaimTemplates:
  - metadata:
      name: mythtv-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1820Gi

