apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /media/lpv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rancher

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /media/lpv2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rancher

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  storageClassName: local-storage
  volumeName: example-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mythtv-configmap
data:
  config.xml: |
    <Configuration>
      <Database>
        <PingHost>1</PingHost>
        <Host>mariadb</Host>
        <UserName>root</UserName>
        <Password>root</Password>
        <DatabaseName>mythconverg</DatabaseName>
        <Port>3306</Port>
      </Database>
      <WakeOnLAN>
        <Enabled>0</Enabled>
        <SQLReconnectWaitTime>0</SQLReconnectWaitTime>
        <SQLConnectRetry>5</SQLConnectRetry>
        <Command>echo 'WOLsqlServerCommand not set'</Command>
      </WakeOnLAN>
    </Configuration>

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-test
spec:
  serviceName: "local-service"
  replicas: 1
  selector:
    matchLabels:
      app: local-test
  template:
    metadata:
      labels:
        app: local-test
    spec:
      containers:
      - name: test-container
        image: willat8/mythtv:20210829
        stdin: true
        tty: true
        command:
        - "/bin/sh"
        volumeMounts:
        - name: local-vol
          mountPath: /usr/test-pod
        - name: mythtv-config
          mountPath: "/root/.mythtv"
      volumes:
      - name: mythtv-config
        configMap:
          name: mythtv-configmap
          items:
          - key: "config.xml"
            path: "config.xml"
  volumeClaimTemplates:
  - metadata:
      name: local-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi

