apiVersion: v1
kind: ConfigMap
metadata:
  name: mythtv-configmap
data:
  config.xml: |
    <Configuration>
      <LocalHostName>mythbackend</LocalHostName>
      <Database>
        <PingHost>1</PingHost>
        <Host>mariadb</Host>
        <UserName>mythtv</UserName>
        <Password>mythtv</Password>
        <DatabaseName>mythconverg</DatabaseName>
        <Port>3306</Port>
      </Database>
      <WakeOnLAN>
        <Enabled>0</Enabled>
        <SQLReconnectWaitTime>0</SQLReconnectWaitTime>
        <SQLConnectRetry>5</SQLConnectRetry>
        <Command>echo 'WOLsqlServerCommand not set'</Command>
      </WakeOnLAN>
    </Configuration>

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mythtv-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mythtv-artwork
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythtv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mythbackend
  template:
    metadata:
      labels:
        app: mythbackend
    spec:
      hostname: mythbackend
      containers:
      - name: mythbackend
        image: australia-southeast1-docker.pkg.dev/cloud-wilhelm/registry/mythtv:latest
        volumeMounts:
        - name: mythtv-data
          mountPath: "/mnt/storage/mythtv"
        - name: mythtv-config
          mountPath: "/root/.mythtv/config.xml"
          subPath: "config.xml"
        - name: mythtv-icons
          mountPath: "/root/.mythtv/channels"
        - name: mythtv-artwork
          mountPath: "/root/.mythtv/artwork"
        - name: shepherd-data
          mountPath: "/shepherd_output"
      initContainers:
      - name: init-mythbackend
        image: busybox
        volumeMounts:
        - name: icons-config
          mountPath: "/icons"
        - name: mythtv-icons
          mountPath: "/root/.mythtv/channels"
        command:
        - "/bin/sh"
        - "-c"
        - "cp /icons/* /root/.mythtv/channels"
      volumes:
      - name: mythtv-config
        configMap:
          name: mythtv-configmap
          items:
          - key: "config.xml"
            path: "config.xml"
      - name: icons-config
        configMap:
          name: icons-configmap
      - name: shepherd-data
        persistentVolumeClaim:
          claimName: shepherd-pv-claim
      - name: mythtv-icons
        emptyDir: {}
      - name: mythtv-data
        persistentVolumeClaim:
          claimName: mythtv-data
      - name: mythtv-artwork
        persistentVolumeClaim:
          claimName: mythtv-artwork
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

---

apiVersion: v1
kind: Service
metadata:
  name: mythbackend
spec:
  selector:
    app: mythbackend
  ports:
    - name: mythbackend-web
      protocol: TCP
      port: 80
      targetPort: 6544
    - name: mythbackend
      protocol: TCP
      port: 6543
      targetPort: 6543
  type: LoadBalancer
  loadBalancerIP: 192.168.0.65

