apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  storageClassName: local-storage
  volumeName: example-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

